// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebeujvmffpprdlrlmmat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZXVqdm1mZnBwcmRscmxtbWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTcwNTMsImV4cCI6MjA3MDAzMzA1M30.ogW6_cEzKnvI4dTpD3vvFetQl_MpTpOeHaC3gvj9Fjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});